name: Build push and deploy to Azure

on:
  push:
    branches:
      - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment: discord-env
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/discord-bot:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/discord-bot:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'              
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/discord-bot:${{ github.sha }}
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            secure-environment-variables: >
                DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
                DICTIONARY_API=${{ secrets.DICTIONARY_API }}
                TRIVIA_API=${{ secrets.TRIVIA_API }}
                TRIVIA_TDB=${{ secrets.TRIVIA_TDB }}
                TRIVIA_TDB_CATEGORIES=${{ secrets.TRIVIA_TDB_CATEGORIES }}
                URBAN_HOST=${{ secrets.URBAN_HOST }}
                URBAN_KEY=${{ secrets.URBAN_KEY }}
                URBAN_URL=${{ secrets.URBAN_URL }}
                PRE_PROMPT=${{ secrets.PRE_PROMPT }}
                CAT_API=${{ secrets.CAT_API }}
            name: discord-bot-deployment
            location: 'west europe'
